#include <llvm/Support/OptimizedStructLayout.h>
#include <mlir/AsmParser/AsmParser.h>
#include <mlir/Dialect/Arith/IR/Arith.h>
#include <mlir/Dialect/ControlFlow/IR/ControlFlow.h>
#include <mlir/Dialect/ControlFlow/IR/ControlFlowOps.h>
#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/Dialect/Index/IR/IndexOps.h>
#include <mlir/Dialect/LLVMIR/LLVMDialect.h>
#include <mlir/Dialect/Math/IR/Math.h>
#include <mlir/IR/Builders.h>
#include <source/CG/ASTIRInterface.hh>
#include <source/CG/CodeGen.hh>
#include <source/Core.hh>
#include <source/Frontend/AST.hh>
#include <source/HLIR/HLIRDialect.hh>

namespace src {
struct CodeGen {
    Module* const mod;
    Context* const ctx;
    mlir::MLIRContext *mctx;
    mlir::OpBuilder builder;
    bool no_verify;

    mlir::Type Int, Bool;

    /// External procedures that we have already declared.
    DenseMap<StringRef, hlir::FuncOp> declared_procedures;

    /// Autogenerated dtors/ctors.
    DenseMap<Expr*, StringRef, TypeBase::DenseMapInfo> destructors;
    DenseMap<Expr*, StringRef, TypeBase::DenseMapInfo> constructors;

    /// Procedure we’re currently emitting.
    ProcDecl* curr_proc{};

    CodeGen(mlir::MLIRContext* mctx, Module* mod, bool no_verify)
        : mod(mod),
          ctx(mod->context),
          mctx(mctx),
          builder(mctx),
          no_verify(no_verify) {
        Int = GetIntType(Type::Int.size(ctx));
        Bool = GetIntType(Size::Bits(1));
    }

    CodeGen(const CodeGen&) = delete;
    CodeGen(CodeGen&&) = delete;
    CodeGen& operator=(const CodeGen&) = delete;
    CodeGen& operator=(CodeGen&&) = delete;

    /// Create an alloca for a local variable.
    [[nodiscard]] auto AllocateLocalVar(LocalDecl* decl) -> mlir::Value;

    /// Attach a block to the end of a region.
    auto Attach(mlir::Region* region, mlir::Block* block) -> mlir::Block*;

    /// Check if a block is closed.
    bool Closed();
    bool Closed(mlir::Block* block);

    /// Construct an object at an address.
    void Construct(
        mlir::Location loc,
        mlir::Value addr,
        Align align,
        ConstructExpr* ctor
    );
    /*
        /// Get the (mangled) name of the constructor of a type.
        auto ScopedPointerCtor(Expr* type) -> std::optional<StringRef>;*/

    template <typename T, typename... Args>
    auto Create(mlir::Location loc, Args&&... args) -> decltype(builder.create<T>(loc, std::forward<Args>(args)...));

    auto CreateInt(mlir::Location loc, const APInt& value, Type type) -> mlir::Value;

    /// Create a function and execute a callback to populate its body.
    template <typename Callable>
    auto CreateProcedure(
        mlir::FunctionType type,
        StringRef name,
        Linkage linkage,
        bool smf,
        Callable callable
    );

    /// Create an external function.
    void CreateExternalProcedure(mlir::FunctionType type, StringRef name);

    /// Destroy an object at an address.
    auto Destroy(mlir::Location loc, mlir::Value addr, Type type) -> mlir::Value;

    /// Get the (mangled) name of the destructor of a type.
    auto Destructor(Type type) -> std::optional<StringRef>;

    auto EmitReference(mlir::Location loc, Expr* decl) -> mlir::Value;

    auto EndLifetime(LocalDecl* decl);

    template <typename Op>
    void GenerateAssignBinOp(BinaryExpr* b);

    template <typename Op>
    void GenerateBinOp(BinaryExpr* b);

    template <typename Op>
    void GenerateCmpOp(BinaryExpr*, mlir::arith::CmpIPredicate pred);

    void Generate(Expr* expr);
    void GenerateModule();
    void GenerateProcedure(ProcDecl* proc);

    /// Get an integer type.
    auto GetIntType(Size width) -> mlir::IntegerType;

    /// Retrieve the static chain pointer for a procedure.
    auto GetStaticChainPointer(ProcDecl* proc) -> mlir::Value;

    /// Perform preprocessing on locals to support nested procedures.
    void InitStaticChain(ProcDecl* proc, hlir::FuncOp f);

    /// Get the MLIR location of a source location.
    auto Loc(Location loc) -> mlir::Location;

    /// Offset a pointer by a constant.
    auto Offset(mlir::Value ptr, i64 value) -> mlir::Value;

    auto Ty(Type type, bool for_closure = false) -> mlir::Type;

    /// Generate a set of operations to unwind from expressions that need unwinding.
    auto UnwindValues(ArrayRef<Expr*> exprs) -> SmallVector<mlir::Value>;
};
} // namespace src

void src::CodeGenModule(mlir::MLIRContext* threads, src::Module* mod, bool no_verify) {
    Assert(not mod->context->has_error(), "Refusing to codegen broken module");
    CodeGen c{threads, mod, no_verify};
    c.GenerateModule();
}

/// ===========================================================================
///  Helpers
/// ===========================================================================
auto src::CodeGen::Loc(Location loc) -> mlir::Location {
    if (not loc.seekable(ctx)) return mlir::UnknownLoc::get(mctx);
    auto lc = loc.seek_line_column(ctx);
    return mlir::FileLineColLoc::get(
        mctx,
        ctx->file(loc.file_id)->path().string(),
        unsigned(lc.line),
        unsigned(lc.col)
    );
}

void src::Module::print_hlir(bool use_generic_assembly_format) const {
    mlir::OpPrintingFlags flags;
    flags.printGenericOpForm(use_generic_assembly_format);
    if (not use_generic_assembly_format) flags.assumeVerified();
    cast<mlir::ModuleOp>(mlir_module_op)->print(llvm::outs(), flags);
}

mlir::ModuleOp src::Module::_mlir() {
    return cast<mlir::ModuleOp>(mlir_module_op);
}

auto src::CodeGen::AllocateLocalVar(LocalDecl* decl) -> mlir::Value {
    /// Captured variables are stored in the static chain area.
    if (decl->captured) return Create<hlir::StructGEPOp>(
        Loc(decl->location),
        decl->parent->captured_locals_ptr,
        decl->capture_index
    );

    return Create<hlir::LocalOp>(
        Loc(decl->location),
        Ty(decl->type),
        decl->type.align(ctx).value(),
        decl->deleted_or_moved
    );
}

auto src::CodeGen::Attach(mlir::Region* region, mlir::Block* block) -> mlir::Block* {
    region->getBlocks().insert(region->end(), block);
    return block;
}

bool src::CodeGen::Closed() {
    return Closed(builder.getBlock());
}

auto ConvertLinkage(src::Linkage l) -> mlir::LLVM::Linkage {
    using L = mlir::LLVM::Linkage;
    switch (l) {
        case src::Linkage::Local:
        case src::Linkage::Internal:
            return L::Private;

        case src::Linkage::Imported:
        case src::Linkage::Exported:
        case src::Linkage::Reexported:
            return L::External;

        case src::Linkage::LinkOnceODR:
            return L::LinkonceODR;
    }
}

template <typename Callable>
auto src::CodeGen::CreateProcedure(
    mlir::FunctionType type,
    StringRef name,
    Linkage linkage,
    bool smf,
    Callable callable
) {
    mlir::OpBuilder::InsertionGuard guard{builder};
    builder.setInsertionPointToEnd(mod->mlir.getBody());
    auto func = Create<hlir::FuncOp>(
        builder.getUnknownLoc(),
        name,
        ConvertLinkage(linkage),
        mlir::LLVM::CConv::C,
        type,
        smf,
        false
    );

    builder.setInsertionPointToEnd(&func.getBody().front());
    return std::invoke(std::forward<Callable>(callable), func);
}

void src::CodeGen::CreateExternalProcedure(mlir::FunctionType type, StringRef name) {
    if (declared_procedures.contains(name)) return;
    CreateProcedure(type, name, Linkage::Imported, false, [&](hlir::FuncOp proc) {
        proc.eraseBody();
        proc.setPrivate();
        declared_procedures[proc.getName()] = proc;
    });
}

bool src::CodeGen::Closed(mlir::Block* block) {
    return not block->empty() and block->back().hasTrait<mlir::OpTrait::IsTerminator>();
}

void src::CodeGen::Construct(
    mlir::Location loc,
    mlir::Value addr,
    Align align,
    ConstructExpr* ctor
) {
    auto args = ctor->args();

    /// Constructors that only construct an entire array take a
    /// pointer to the array, not a pointer to an element, so we
    /// need to decay the pointer in that case.
    auto LowerElemPtr = [&] {
        while (
            ctor->array_ctor() and
            isa<hlir::ArrayType>(cast<hlir::ReferenceType>(addr.getType()).getElem())
        ) addr = Create<hlir::ArrayDecayOp>(loc, addr);
    };

    switch (ctor->ctor_kind) {
        /// Handled elsewhere.
        case ConstructKind::MoveParameter: Unreachable();

        /// Perform no initialisation at all.
        case ConstructKind::Uninitialised: break;

        /// Zero-initialisation is accomplished by creating a ConstructOp
        /// with no arguments other than the object itself.
        case ConstructKind::Zeroinit:
        case ConstructKind::ArrayZeroinit: {
            LowerElemPtr();
            Create<hlir::ConstructOp>(
                loc,
                addr,
                mlir::ValueRange{},
                ctor->elems()
            );
        } break;

        /// A trivial copy is always one argument.
        case ConstructKind::TrivialCopy:
        case ConstructKind::ArrayBroadcast: {
            Assert(args.size() == 1);
            Generate(args.front());
            LowerElemPtr();
            Create<hlir::ConstructOp>(
                loc,
                addr,
                args.front()->mlir,
                ctor->elems()
            );
        } break;

        /// Create a slice from a reference+size.
        case ConstructKind::SliceFromParts: {
            Assert(args.size() == 2);
            Generate(args[0]);
            Generate(args[1]);
            auto slice = Create<hlir::LiteralOp>(
                loc,
                hlir::SliceType::get(Ty(cast<ReferenceType>(args[0]->type)->elem)),
                args[0]->mlir,
                args[1]->mlir
            );

            Create<hlir::StoreOp>(
                loc,
                addr,
                slice,
                align.value()
            );
        } break;

        case ConstructKind::InitialiserCall:
        case ConstructKind::ArrayInitialiserCall: {
            for (auto a : args) Generate(a);
            SmallVector<mlir::Value> arguments;
            for (auto a : args) arguments.push_back(a->mlir);
            LowerElemPtr();
            Create<hlir::ConstructOp>(
                loc,
                addr,
                ctor->init()->mangled_name,
                arguments,
                ctor->elems()
            );
        } break;

        case ConstructKind::ArrayListInit: {
            addr = Create<hlir::ArrayDecayOp>(loc, addr);
            for (auto [i, c] : llvm::enumerate(ctor->args())) Construct(
                loc,
                Offset(addr, i64(i)),
                align,
                cast<ConstructExpr>(c)
            );
        } break;
    }
}

/*auto src::CodeGen::Constructor(Expr* type) -> std::optional<StringRef> {
    if (not isa<ScopedPointerType>(type)) return std::nullopt;

    /// Auto-generate constructors for scoped pointers.
    if (auto sc = cast<ScopedPointerType>(type)) {
        if (auto d = constructors.find(sc); d != constructors.end())
            return d->second;

        /// Create a new function.
        ///
        /// A constructor always takes a reference to the type being constructed.
        auto fty = mlir::FunctionType::get(mctx, hlir::ReferenceType::get(Ty(sc)), {});
        auto name = fmt::format("_SK{}", sc.mangled_name(ctx));
        auto proc = CreateProcedure(fty, name, Linkage::LinkOnceODR, [&](hlir::FuncOp f) {
            /// Allocate the pointer.
            auto ptr = Create<hlir::NewOp>(
                builder.getUnknownLoc(),
                hlir::ReferenceType::get(Ty(sc->elem))
            );

            /// Store it in the reference.
            Create<hlir::StoreOp>(
                builder.getUnknownLoc(),
                f.getArgument(0),
                ptr.getResult(),
                sc.align(mod) / 8
            );

            /// Call the element type’s constructor, if any.
            Construct(builder.getUnknownLoc(), ptr.getResult(), sc->elem);

            /// Done.
            Create<hlir::ReturnOp>(builder.getUnknownLoc());
            return f;
        });

        /// Save it for later.
        return constructors[sc] = proc.getName();
    }

    Unreachable();
}*/

template <typename T, typename... Args>
auto src::CodeGen::Create(mlir::Location loc, Args&&... args) -> decltype(builder.create<T>(loc, std::forward<Args>(args)...)) {
    if (auto b = builder.getBlock(); not b->empty() and b->back().hasTrait<mlir::OpTrait::IsTerminator>()) {
        /// If the block is already closed, create a new one, or
        /// simply drop the instruction if it is a terminator.
        if constexpr (T::template hasTrait<mlir::OpTrait::IsTerminator>()) return {};
        builder.createBlock(b->getParent());
    }

    /// Create the instruction.
    return builder.create<T>(loc, std::forward<Args>(args)...);
}

auto src::CodeGen::CreateInt(mlir::Location loc, const APInt& value, Type type) -> mlir::Value {
    type = type.desugared;

    /// Explicit-width integer types.
    if (auto int_ty = dyn_cast<IntType>(type)) {
        if (int_ty->size.bits() > 64) Todo("Create > 64 bit integer constant");
        return Create<mlir::arith::ConstantIntOp>(
            loc,
            value.getZExtValue(),
            mlir::IntegerType::get(mctx, unsigned(int_ty->size.bits()))
        );
    }

    /// `int` type.
    else if (type == Type::Int) {
        return Create<mlir::arith::ConstantOp>(
            loc,
            Ty(Type::Int),
            builder.getI64IntegerAttr(i64(value.getZExtValue()))
        );
    }

    /// Invalid.
    else { Unreachable("Cannot create an integer constant of type {}", type.str(true)); }
}

auto src::CodeGen::Destroy(mlir::Location loc, mlir::Value addr, Type type) -> mlir::Value {
    auto d = Destructor(type);
    if (not d.has_value()) return {};
    return Create<hlir::DestroyOp>(
        loc,
        addr,
        *d
    );
}

auto src::CodeGen::Destructor(Type type) -> std::optional<StringRef> {
    if (not isa<ScopedPointerType>(type)) return std::nullopt;

    /// Auto-generate destructors for scoped pointers.
    if (auto sc = dyn_cast<ScopedPointerType>(type)) {
        if (auto d = destructors.find(sc); d != destructors.end())
            return d->second;

        /// Create a new function.
        ///
        /// A destructor always takes a reference to the type being destroyed.
        auto fty = mlir::FunctionType::get(mctx, hlir::ReferenceType::get(Ty(sc)), {});
        auto name = fmt::format("_SX{}", Type(sc).mangled_name);
        auto proc = CreateProcedure(fty, name, Linkage::LinkOnceODR, true, [&](hlir::FuncOp f) {
            /// Load the pointer.
            auto ptr = Create<hlir::LoadOp>(builder.getUnknownLoc(), f.getImplicitThis());

            /// Call the element type’s destructor, if any.
            Destroy(builder.getUnknownLoc(), ptr.getResult(), sc->elem);

            /// Delete the pointer.
            Create<hlir::DeleteOp>(builder.getUnknownLoc(), ptr.getResult());

            /// Done.
            Create<hlir::ReturnOp>(builder.getUnknownLoc());
            return f;
        });

        /// Save it for later.
        return destructors[sc] = proc.getName();
    }

    Unreachable();
}

auto src::CodeGen::EmitReference([[maybe_unused]] mlir::Location loc, src::Expr* decl) -> mlir::Value {
    /// If the operand is a function, create a function constant.
    if (auto p = dyn_cast<ProcDecl>(decl)) return Create<mlir::func::ConstantOp>(
        loc,
        Ty(p->type),
        mlir::SymbolRefAttr::get(mctx, p->mangled_name)
    );

    Unreachable();
}

auto src::CodeGen::EndLifetime([[maybe_unused]] LocalDecl* decl) {
    Todo();
}

void src::CodeGen::InitStaticChain(ProcDecl* proc, hlir::FuncOp func) {
    if (proc->captured_locals.empty() and not proc->takes_static_chain) return;

    /// Collect all captured variables; static chain is first.
    SmallVector<llvm::OptimizedStructLayoutField, 10> captured;
    if (proc->takes_static_chain) captured.push_back({
        nullptr,
        8,              /// FIXME: Get size of pointer type from context.
        llvm::Align(8), /// FIXME: Get alignment of pointer type from context.
        0,
    });

    /// Add a field for each captured variable.
    for (auto v : proc->captured_locals) {
        captured.push_back({
            v,
            u64(v->type.size(ctx).bytes()),
            v->type.align(ctx),
            llvm::OptimizedStructLayoutField::FlexibleOffset,
        });
    }

    /// Optimise the layout.
    const auto [size, align] = llvm::performOptimizedStructLayout(captured);

    /// Combine the allocas to a struct type. Even though the offsets of
    /// all fields are known, we may still need to emit padding to align
    /// each field to its required offset since LLVM doesn’t know anything
    /// about the offsets.
    SmallVector<StructType::Field> fields;
    Size total_size;
    for (const auto& [i, var] : llvm::enumerate(captured)) {
        /// Zero is the static chain.
        if (proc->takes_static_chain and i == 0) {
            fields.emplace_back(
                "",
                new (mod) ReferenceType(proc->parent->captured_locals_type, {}),
                Size::Bytes(0),
                false
            );

            total_size += Size::Bytes(8); /// FIXME: Get pointer alignment from context.
            continue;
        }

        /// Anything else is a captured local. Note: const_cast is
        /// safe here because we passed in non-const LocalDecl*’s
        /// above.
        auto v = static_cast<LocalDecl*>(const_cast<void*>(var.Id));
        v->capture_index = isz(i);

        /// Insert padding if required.
        if (total_size.bytes() != var.Offset) {
            v->capture_index++;
            fields.emplace_back(
                "",
                ArrayType::GetByteArray(mod, isz(usz(var.Offset) - total_size.bytes())),
                total_size,
                true
            );
        }

        total_size = Size::Bytes(var.Offset) + v->type.size(ctx);
        fields.emplace_back(
            "",
            v->type,
            Size::Bytes(var.Offset),
            false
        );
    }

    /// Create a struct type and finalise it.
    auto s = new (mod) StructType(mod, "", std::move(fields), {}, nullptr, Mangling::Source, {});

    /// The alignment and size are just set to what LLVM’s algorithm told us
    /// they should be. In particular, we need *not* ensure that the size is
    /// a multiple of the alignment, as we will never have an array of these
    /// anyway.
    s->stored_alignment = align;
    s->stored_size = Size::Bytes(size);
    s->sema.set_done();

    /// Associate it with the procedure and create the vars area.
    proc->captured_locals_type = s;
    proc->captured_locals_ptr = Create<hlir::LocalOp>(
        builder.getUnknownLoc(),
        Ty(s),
        s->stored_alignment.value(),
        false
    );

    /// Save the parent’s chain pointer if there is one.
    if (proc->takes_static_chain) {
        Assert(func.getNumArguments() == proc->params.size() + 1);

        /// Save the pointer.
        Create<hlir::StoreOp>(
            builder.getUnknownLoc(),
            proc->captured_locals_ptr,
            func.getExplicitArgument(u32(proc->params.size())), /// (!)
            8                                                   /// FIXME: Get alignment of pointer type from context.
        );
    }
}

auto src::CodeGen::Offset(mlir::Value ptr, i64 value) -> mlir::Value {
    if (value == 0) return ptr;
    return Create<hlir::OffsetOp>(
        ptr.getLoc(),
        ptr,
        Create<mlir::index::ConstantOp>(ptr.getLoc(), value)
    );
}

auto src::CodeGen::GetIntType(Size width) -> mlir::IntegerType {
    return mlir::IntegerType::get(mctx, unsigned(width.bits()));
}

auto src::CodeGen::GetStaticChainPointer(ProcDecl* proc) -> mlir::Value {
    /// Current procedure.
    if (curr_proc == proc) {
        Assert(proc->captured_locals_ptr);
        return proc->captured_locals_ptr;
    }

    /// Load the parent’s chain pointer.
    mlir::Value chain = Create<hlir::ChainExtractLocalOp>(
        builder.getUnknownLoc(),
        curr_proc->captured_locals_ptr,
        0
    );

    /// Walk up the stack till we reach the desired procedure.
    for (auto p = curr_proc->parent; p != proc; p = p->parent) {
        chain = Create<hlir::ChainExtractLocalOp>(
            builder.getUnknownLoc(),
            chain,
            0
        );
    }

    return chain;
}

auto src::CodeGen::Ty(Type type, bool for_closure) -> mlir::Type {
    Assert(isa<TypeBase>(type), "Type is not a Type");
    switch (type->kind) {
        case Expr::Kind::BuiltinType: {
            switch (cast<BuiltinType>(type)->builtin_kind) {
                using K = BuiltinTypeKind;
                case K::Void: return mlir::NoneType::get(mctx);
                case K::NoReturn: return mlir::NoneType::get(mctx);
                case K::Bool: return Bool;
                case K::Int: return Int;
                case K::Unknown:
                case K::OverloadSet:
                case K::ArrayLiteral:
                    Unreachable();
            }
            Unreachable();
        }

        case Expr::Kind::IntType: {
            auto ty = cast<IntType>(type);
            return mlir::IntegerType::get(mctx, unsigned(ty->size.bits()));
        }

        case Expr::Kind::SliceType: {
            auto ty = cast<SliceType>(type);
            return hlir::SliceType::get(Ty(ty->elem));
        }

        case Expr::Kind::ReferenceType:
        case Expr::Kind::ScopedPointerType: {
            auto ty = cast<SingleElementTypeBase>(type);

            /// References to `none` are not really well-formed...
            auto elem = ty->elem == Type::Void ? Type::I8 : ty->elem;
            return hlir::ReferenceType::get(Ty(elem));
        }

        case Expr::Kind::ArrayType: {
            auto ty = cast<ArrayType>(type);
            return hlir::ArrayType::get(Ty(ty->elem), ty->dimension().getZExtValue());
        }

        case Expr::Kind::SugaredType:
        case Expr::Kind::ScopedType: {
            auto ty = cast<SingleElementTypeBase>(type);
            return Ty(ty->elem);
        }

        case Expr::Kind::ClosureType:
            return hlir::ClosureType::get(Ty(cast<ClosureType>(type)->proc_type, true));

        case Expr::Kind::OpaqueType:
            return mlir::LLVM::LLVMStructType::getOpaque(type.mangled_name, mctx);

        case Expr::Kind::ProcType: {
            auto ty = cast<ProcType>(type);
            SmallVector<mlir::Type> params;

            /// Sanity check.
            Assert(not ty->is_init or not ty->static_chain_parent, "Initialisers can’t be nested procedures");

            /// Add implicit this parameter, if any.
            if (ty->is_init) params.push_back(hlir::ReferenceType::get(Ty(ty->init_of)));

            /// Add regular parameters.
            for (auto p : ty->param_types) params.push_back(Ty(p));

            /// Add an extra parameter for the static chain pointer, unless
            /// this is for a closure type, in which case the environment
            /// will already be added anyway.
            if (not for_closure and ty->static_chain_parent) {
                Assert(ty->static_chain_parent->captured_locals_type);
                params.push_back(hlir::ReferenceType::get(Ty(ty->static_chain_parent->captured_locals_type)));
            }

            /// To ‘return void’, we have to set no return type at all.
            if (not ty->ret_type.yields_value) return mlir::FunctionType::get(mctx, params, {});
            else return mlir::FunctionType::get(mctx, params, Ty(ty->ret_type));
        }

        case Expr::Kind::OptionalType: {
            auto opt = cast<OptionalType>(type);
            if (auto ref = dyn_cast<ReferenceType>(opt->elem))
                return hlir::OptRefType::get(Ty(ref->elem));
            Todo();
        }

        case Expr::Kind::StructType: {
            auto s = cast<StructType>(type);
            if (s->mlir) return s->mlir;

            /// Handle recursion.
            if (not s->name.empty())
                s->mlir = mlir::LLVM::LLVMStructType::getIdentified(mctx, s->name);

            /// Collect element types.
            auto range = s->field_types() | vws::transform([&](auto& t) { return Ty(t); });
            SmallVector<mlir::Type> elements{range.begin(), range.end()};

            /// Named struct.
            if (not s->name.empty()) {
                auto ok = cast<mlir::LLVM::LLVMStructType>(s->mlir).setBody(elements, false);
                if (mlir::failed(ok)) Diag::ICE(ctx, s->location, "Could not convert struct type to HLIR");
            }

            /// Literal struct.
            else {
                s->mlir = mlir::LLVM::LLVMStructType::getLiteral(
                    mctx,
                    elements,
                    false
                );
            }

            return s->mlir;
        }

        case Expr::Kind::Nil:
            Diag::ICE(ctx, type->location, "Nil type has no representation in the IR");

        SOURCE_NON_TYPE_EXPRS:
            Unreachable("Not a type");
    }

    Unreachable();
}

auto src::CodeGen::UnwindValues(ArrayRef<Expr*> exprs) -> SmallVector<mlir::Value> {
    SmallVector<mlir::Value> vals;
    for (auto e : exprs) {
        if (isa<DeferExpr>(e)) vals.push_back(e->mlir);
        else if (auto l = dyn_cast<LocalDecl>(e)) {
            auto d = Destroy(Loc(l->location), l->mlir, l->type);
            if (d) vals.push_back(d);
        }
    }
    return vals;
}

/// ===========================================================================
///  Code Generation
/// ===========================================================================
void src::CodeGen::Generate(src::Expr* expr) {
    if (expr->emitted) return;
    expr->emitted = true;
    switch (expr->kind) {
        case Expr::Kind::BuiltinType:
        case Expr::Kind::IntType:
        case Expr::Kind::ReferenceType:
        case Expr::Kind::ScopedPointerType:
        case Expr::Kind::SliceType:
        case Expr::Kind::OptionalType:
        case Expr::Kind::ProcType:
        case Expr::Kind::ClosureType:
        case Expr::Kind::ArrayType:
        case Expr::Kind::SugaredType:
        case Expr::Kind::ScopedType:
        case Expr::Kind::OpaqueType:
            Unreachable();

        case Expr::Kind::OverloadSetExpr:
            Diag::ICE(ctx, expr->location, "Unresolved overload set in codegen");

        /// These are no-ops.
        case Expr::Kind::StructType:
        case Expr::Kind::ModuleRefExpr:
        case Expr::Kind::EmptyExpr:
        case Expr::Kind::AliasExpr:
            break;

        case Expr::Kind::ConstructExpr:
            Todo();

        /// Nil should always be wrapped in a cast expression.
        case Expr::Kind::Nil:
            Diag::ICE(ctx, expr->location, "Nil has no representation in the IR");

        case Expr::Kind::InvokeExpr: {
            auto e = cast<InvokeExpr>(expr);
            Generate(e->callee);

            /// Emit args.
            SmallVector<mlir::Value> args;
            for (auto a : e->args) {
                Generate(a);
                args.push_back(a->mlir);
            }

            /// If the callee is a procedure decl, call it directly.
            if (auto proc = dyn_cast<mlir::func::ConstantOp>(e->callee->mlir.getDefiningOp())) {
                /// If the callee takes a static chain pointer, retrieve
                /// it and add it to the argument list.
                if (auto chain = cast<ProcType>(e->callee->type)->static_chain_parent)
                    args.push_back(GetStaticChainPointer(chain));

                /// Create the call.
                auto call_op = Create<hlir::CallOp>(
                    Loc(e->location),
                    cast<mlir::FunctionType>(proc.getType()).getResults(),
                    proc.getValue(),
                    false,
                    mlir::LLVM::CConv::C,
                    args
                );

                /// The operation only has a result if the function’s
                /// return type is not void.
                if (e->type.yields_value) e->mlir = call_op.getYield();
            }

            /// If the callee is a closure, then use a special operation for that.
            else if (auto c = dyn_cast<ClosureType>(e->callee->type)) {
                auto call_op = Create<hlir::InvokeClosureOp>(
                    Loc(e->location),
                    e->type.yields_value ? mlir::TypeRange{Ty(e->type)} : mlir::TypeRange{},
                    e->callee->mlir,
                    args
                );

                /// The operation only has a result if the function’s
                /// return type is not void.
                if (e->type.yields_value) e->mlir = call_op.getResult();
            }

            else {
                Unreachable("Indirect calls must be closure calls.");
            }
        } break;

        case Expr::Kind::InvokeBuiltinExpr: {
            auto i = cast<InvokeBuiltinExpr>(expr);
            switch (i->builtin) {
                case Builtin::New: {
                    i->mlir = Create<hlir::NewOp>(
                        Loc(i->location),
                        hlir::ReferenceType::get(Ty(i->type))
                    );
                    return;
                }

                /// Delete calls the destructor of an object.
                case Builtin::Destroy: {
                    Generate(i->args[0]);
                    auto var = cast<LocalRefExpr>(i->args[0])->decl;
                    EndLifetime(var);
                    return;
                }
            }

            Unreachable();
        }

        case Expr::Kind::ParenExpr: {
            auto p = cast<ParenExpr>(expr);
            Generate(p->expr);
            p->mlir = p->expr->mlir;
        } break;

        case Expr::Kind::DeclRefExpr: {
            auto e = cast<DeclRefExpr>(expr);
            e->mlir = EmitReference(Loc(e->location), e->decl);
        } break;

        case Expr::Kind::LocalRefExpr: {
            auto var = cast<LocalRefExpr>(expr);

            /// Easy case: the variable we’re accessing is in the same
            /// scope as the reference.
            if (var->parent == var->decl->parent) {
                Assert(var->decl->mlir);
                var->mlir = var->decl->mlir;
            }

            /// This is the complicated one. We need to retrieve the
            /// address of this variable (note that this is an lvalue!)
            /// via the static chain.
            else {
                /// Get the frame pointer of the procedure containing
                /// the variable declaration.
                auto& locals = var->decl->parent->captured_locals;
                auto var_index = std::distance(locals.begin(), rgs::find(locals, var->decl));
                var->mlir = Create<hlir::StructGEPOp>(
                    Loc(var->location),
                    GetStaticChainPointer(var->decl->parent),
                    var_index + var->decl->parent->nested
                );
            }
        } break;

        case Expr::Kind::MemberAccessExpr: {
            /// Emit the base object.
            auto e = cast<MemberAccessExpr>(expr);
            Generate(e->object);

            /// The object may be an lvalue; if so, yield the address
            /// rather than loading the entire object.
            if (e->object->is_lvalue) {
                Assert(e->is_lvalue, "Accessing a member of an lvalue should yield an lvalue");
                Assert(e->field, "Struct field not set for member access");
                e->mlir = Create<hlir::StructGEPOp>(
                    Loc(e->location),
                    e->object->mlir,
                    e->field->index
                );
            }

            /// Object is an rvalue.
            else {
                /// Member of a slice.
                if (isa<SliceType>(e->object->type)) {
                    if (e->member == "data") {
                        e->mlir = Create<hlir::SliceDataOp>(
                            Loc(e->location),
                            e->object->mlir
                        );
                    } else if (e->member == "size") {
                        e->mlir = Create<hlir::SliceSizeOp>(
                            Loc(e->location),
                            Ty(Type::Int),
                            e->object->mlir
                        );
                    } else {
                        Unreachable();
                    }
                } else {
                    Unreachable();
                }
            }
        } break;

        case Expr::Kind::ScopeAccessExpr: {
            auto sa = cast<ScopeAccessExpr>(expr);
            Generate(sa->object);
            sa->mlir = EmitReference(Loc(sa->location), sa->resolved);
        } break;

        case Expr::Kind::CastExpr: {
            auto c = cast<CastExpr>(expr);

            /// Emit the operand.
            if (not isa<Nil>(c->operand)) Generate(c->operand);

            /// Note that some of the casts perform the same operation,
            /// but they are logically distinct in that they yield different
            /// types and value categories at the AST level.
            switch (c->cast_kind) {
                /// Load a value or a reference.
                case CastKind::LValueRefToLValue:
                case CastKind::LValueToRValue: {
                    Assert(c->operand->is_lvalue);
                    c->mlir = Create<hlir::LoadOp>(
                        Loc(c->location),
                        c->operand->mlir
                    );
                } break;

                /// Reference <-> LValue; Nop
                ///
                /// These are logical operations only and no-ops
                /// at the IR level.
                case CastKind::ReferenceToLValue:
                case CastKind::LValueToReference:
                    c->mlir = c->operand->mlir;
                    break;

                /// Technically a no-op, but the type is different.
                case CastKind::ArrayToElemRef:
                    c->mlir = Create<hlir::ArrayDecayOp>(
                        Loc(c->location),
                        c->operand->mlir
                    );
                    break;

                /// Test if an optional is nil.
                case CastKind::OptionalNilTest: {
                    auto opt = cast<OptionalType>(c->operand->type);

                    /// Compare optional references against null.
                    if (isa<ReferenceType>(opt->elem)) {
                        auto nil = Create<hlir::NilOp>(Loc(c->operand->location), Ty(opt->elem));
                        c->mlir = Create<hlir::PointerNeOp>(
                            Loc(c->location),
                            c->operand->mlir,
                            nil
                        );
                        break;
                    }

                    Todo();
                }

                /// Access the value of an optional.
                case CastKind::OptionalUnwrap: {
                    auto opt = cast<OptionalType>(c->operand->type);

                    /// No-op for optional references.
                    if (isa<ReferenceType>(opt->elem)) {
                        auto res = c->is_lvalue
                                     ? hlir::ReferenceType::get(Ty(opt->elem))
                                     : Ty(opt->elem);

                        c->mlir = Create<hlir::BitCastOp>(
                            Loc(c->location),
                            res,
                            c->operand->mlir
                        );
                        break;
                    }

                    Todo();
                }

                /// Create an optional from a value.
                case CastKind::OptionalWrap: {
                    auto opt = cast<OptionalType>(c->type);

                    /// No-op for optional references. This is always an rvalue.
                    if (isa<ReferenceType>(opt->elem)) {
                        c->mlir = Create<hlir::BitCastOp>(
                            Loc(c->location),
                            Ty(c->type),
                            c->operand->mlir
                        );
                        break;
                    }

                    Todo();
                }

                /// Proper casts are all handled the same.
                case CastKind::Implicit:
                case CastKind::Soft:
                case CastKind::Hard: {
                    /// Create a nil of the target type.
                    if (isa<Nil>(c->operand)) {
                        c->mlir = Create<hlir::NilOp>(Loc(c->location), Ty(c->type));
                    }

                    /// No-op.
                    else if (c->operand->type == c->type) {
                        c->mlir = c->operand->mlir;
                    }

                    /// Procedure to closure casts.
                    else if (isa<ProcType>(c->operand->type) and isa<ClosureType>(c->type)) {
                        auto proc = c->operand->mlir.getDefiningOp<mlir::func::ConstantOp>();
                        auto proc_type = cast<ProcType>(c->operand->type);

                        /// If the procedure is a nested function that takes a static
                        /// chain, retrieve the appropriate chain pointer.
                        if (proc_type->static_chain_parent) {
                            auto chain = GetStaticChainPointer(proc_type->static_chain_parent);
                            c->mlir = Create<hlir::MakeClosureOp>(
                                Loc(c->location),
                                proc.getValue(),
                                Ty(c->type),
                                chain
                            );
                        }

                        /// Otherwise, leave the data pointer empty; the backend will
                        /// set it to null during lowering.
                        else {
                            c->mlir = Create<hlir::MakeClosureOp>(
                                Loc(c->location),
                                proc.getValue(),
                                Ty(c->type)
                            );
                        }
                    }

                    /// Integer-to-integer casts.
                    else if (c->operand->type.is_int(true) and c->type.is_int(true)) {
                        auto from_size = c->operand->type.size(ctx);
                        auto to_size = c->type.size(ctx);

                        /// Truncation.
                        if (from_size > to_size) {
                            /// Casts to bool never actually truncate, but are instead
                            /// equivalent to != 0. Note that that only applies to bool,
                            /// not i1!
                            if (c->type == Type::Bool) {
                                auto int_type = mlir::IntegerType::get(mctx, unsigned(from_size.bits()));
                                auto zero = Create<mlir::arith::ConstantOp>(
                                    Loc(c->location),
                                    int_type,
                                    mlir::IntegerAttr::get(int_type, 0)
                                );

                                c->mlir = Create<mlir::arith::CmpIOp>(
                                    Loc(c->location),
                                    mlir::IntegerType::get(mctx, 1),
                                    mlir::arith::CmpIPredicate::ne,
                                    c->operand->mlir,
                                    zero
                                );
                            } else {
                                c->mlir = Create<mlir::arith::TruncIOp>(
                                    Loc(c->location),
                                    mlir::IntegerType::get(mctx, unsigned(to_size.bits())),
                                    c->operand->mlir
                                );
                            }

                        }

                        /// Extension.
                        else if (from_size < to_size) {
                            /// Since all of our integers are signed, we always use sign
                            /// extension, except that, if we’re extending an i1, we use
                            /// zero-extension, as in case of an i1 with the value 1 (true)
                            /// sign-extension would yield -1 instead of 1.
                            if (from_size.bits() == 1) {
                                c->mlir = Create<mlir::arith::ExtUIOp>(
                                    Loc(c->location),
                                    mlir::IntegerType::get(mctx, unsigned(to_size.bits())),
                                    c->operand->mlir
                                );
                            } else {
                                c->mlir = Create<mlir::arith::ExtSIOp>(
                                    Loc(c->location),
                                    mlir::IntegerType::get(mctx, unsigned(to_size.bits())),
                                    c->operand->mlir
                                );
                            }
                        }

                        /// No-op.
                        else {
                            c->mlir = c->operand->mlir;
                        }
                    }

                    else {
                        Diag::ICE(
                            ctx,
                            c->location,
                            "Unsupported cast from {} to {} in backend",
                            c->operand->type.str(true),
                            c->type.str(true)
                        );
                    }
                }
            }
        } break;

        case Expr::Kind::ConstExpr: {
            auto c = cast<ConstExpr>(expr);
            Assert(c->value.is_int(), "Can only generate integer constant expressions");
            c->mlir = CreateInt(Loc(c->location), c->value.as_int(), c->type);
        } break;

        case Expr::Kind::DeferExpr: {
            auto d = Create<hlir::DeferOp>(Loc(expr->location));
            expr->mlir = d;
            mlir::OpBuilder::InsertionGuard guard{builder};
            builder.setInsertionPointToEnd(&d.getBody().front());
            Generate(cast<DeferExpr>(expr)->expr);
            if (not Closed(builder.getBlock())) Create<hlir::YieldOp>(
                builder.getUnknownLoc(),
                mlir::Value{},
                mlir::ValueRange{}
            );
        } break;

        case Expr::Kind::LoopControlExpr: {
            auto l = cast<LoopControlExpr>(expr);
            const auto loc = Loc(expr->location);

            /// Emit the branch.
            Create<hlir::DirectBrOp>(
                loc,
                l->is_continue ? l->target->continue_block : l->target->break_block,
                UnwindValues(l->unwind)
            );
        } break;

        case Expr::Kind::GotoExpr: {
            auto g = cast<GotoExpr>(expr);

            Create<hlir::DirectBrOp>(
                Loc(g->location),
                g->target->block,
                UnwindValues(g->unwind)
            );
        } break;

        case Expr::Kind::LabelExpr: {
            auto l = cast<LabelExpr>(expr);

            /// Insert the block that we’ve already created for this label.
            if (l->used) {
                Create<mlir::cf::BranchOp>(
                    Loc(l->location),
                    l->block
                );

                builder.getBlock()->getParent()->push_back(l->block);
                builder.setInsertionPointToEnd(l->block);
            }

            /// Emit the labelled expression.
            Generate(l->expr);
        } break;

        /// Nothing to do here other than emitting the underlying decl.
        case Expr::Kind::ExportExpr: {
            auto e = cast<ExportExpr>(expr);

            /// Do not attempt to emit procedures here.
            if (not isa<ProcDecl>(e->expr)) Generate(e->expr);
        } break;

        case Expr::Kind::ReturnExpr: {
            auto r = cast<ReturnExpr>(expr);
            if (r->value) Generate(r->value);

            /// Return the value.
            if (not Closed()) {
                Create<hlir::ReturnOp>(
                    Loc(r->location),
                    r->value ? r->value->mlir : mlir::Value{},
                    UnwindValues(r->unwind)
                );
            }
        } break;

        /// There is no AssertOp in HLIR since assertions require control flow.
        case Expr::Kind::AssertExpr: {
            auto a = cast<AssertExpr>(expr);
            Generate(a->cond);

            /// Only emit assertion message if the assertion fails.
            auto r = builder.getBlock()->getParent();
            auto loc = Loc(a->location);
            auto fail = new mlir::Block;
            auto cont = new mlir::Block;
            Create<mlir::cf::CondBranchOp>(
                loc,
                a->cond->mlir,
                cont,
                fail
            );

            /// Failure case.
            mlir::Value message;
            r->getBlocks().insertAfter(builder.getBlock()->getIterator(), fail);
            builder.setInsertionPointToEnd(fail);

            /// Emit message.
            if (a->msg) {
                Generate(a->msg);
                message = a->msg->mlir;
            } else {
                message = Create<hlir::NilOp>(
                    loc,
                    hlir::SliceType::get(Ty(Type::I8))
                );
            }

            /// export proc __src_assert_fail(
            ///     i8[] cond,
            ///     i8[] message,
            ///     i8[] file,
            ///     int line,
            ///     int col
            /// )
            auto lc = a->location.seek_line_column(ctx);
            auto line = Create<mlir::arith::ConstantIntOp>(loc, lc.line, Type::Int.size(ctx).bits());
            auto col = Create<mlir::arith::ConstantIntOp>(loc, lc.col, Type::Int.size(ctx).bits());
            Generate(a->cond_str);
            Generate(a->file_str);

            mlir::Value args[]{
                a->cond_str->mlir,
                message,
                a->file_str->mlir,
                line,
                col,
            };

            Create<hlir::CallOp>(
                loc,
                mlir::TypeRange{},
                "__src_assert_fail",
                false,
                mlir::LLVM::CConv::C,
                args
            );

            /// Should never return.
            Create<hlir::UnreachableOp>(loc);

            /// Continue as normal.
            r->getBlocks().insertAfter(builder.getBlock()->getIterator(), cont);
            builder.setInsertionPointToEnd(cont);
        } break;

        case Expr::Kind::BlockExpr: {
            auto e = cast<BlockExpr>(expr);
            if (e->exprs.empty()) break;

            /// Create a scope for the block.
            const bool yields_value = e->type.yields_value;
            auto b = Create<hlir::ScopeOp>(
                Loc(e->location),
                not yields_value ? mlir::Type{}
                : e->is_lvalue   ? hlir::ReferenceType::get(Ty(e->type))
                                 : Ty(e->type)
            );

            /// Associate block with scope op.
            e->scope_op = b;

            /// Insert in scope.
            mlir::OpBuilder::InsertionGuard guard{builder};
            builder.setInsertionPointToEnd(&b.getBody().front());

            /// Emit expressions.
            ///
            /// Note that some expressions—e.g. ProcDecls are not emitted
            /// at block scope because there is either no point in that,
            /// or really no way of doing so (for instance, how are we
            /// supposed to emit a module reference at block scope?).
            for (auto s : e->exprs) {
                if (isa<ProcDecl, OverloadSetExpr, ModuleRefExpr, AliasExpr, TypeBase>(s)) continue;
                Generate(s);
            }

            /// Determine yield.
            if (yields_value) e->mlir = b.getRes();
            if (not Closed(builder.getBlock())) {
                Create<hlir::YieldOp>(
                    Loc(e->location),
                    yields_value ? e->exprs.back()->mlir : mlir::Value{},
                    UnwindValues(e->unwind)
                );
            }
        } break;

        case Expr::Kind::StringLiteralExpr: {
            auto str = cast<StrLitExpr>(expr);

            /// Create a global ref to the string data. This returns
            /// a reference to an array of chars.
            auto str_value = mod->strtab[str->index];
            auto i8 = mlir::IntegerType::get(mctx, 8);
            auto str_arr = Create<hlir::GlobalRefOp>(
                Loc(str->location),
                hlir::ReferenceType::get(hlir::ArrayType::get(i8, str_value.size())),
                mlir::SymbolRefAttr::get(mctx, fmt::format(".str.data.{}", str->index))
            );

            /// Insert a conversion from i8[size]& to i8&.
            auto str_ptr = Create<hlir::ArrayDecayOp>(
                Loc(str->location),
                str_arr
            );

            /// Create an integer holding the string size.
            auto str_size = Create<mlir::index::ConstantOp>(
                Loc(str->location),
                mod->strtab[str->index].size() - 1 /// Exclude null terminator.
            );

            /// Create a slice.
            str->mlir = Create<hlir::LiteralOp>(
                Loc(str->location),
                hlir::SliceType::get(i8),
                str_ptr,
                str_size
            );
        } break;

        /// Create a bool constant.
        case Expr::Kind::BoolLiteralExpr: {
            auto e = cast<BoolLitExpr>(expr);
            e->mlir = Create<mlir::arith::ConstantIntOp>(
                Loc(e->location),
                e->value,
                mlir::IntegerType::get(mctx, 1)
            );
        } break;

        /// Create an integer constant.
        case Expr::Kind::IntegerLiteralExpr: {
            auto e = cast<IntLitExpr>(expr);
            e->mlir = CreateInt(Loc(e->location), e->value, e->type);
        } break;

        case Expr::Kind::ArrayLiteralExpr: Todo();

        case Expr::Kind::LocalDecl: {
            auto e = cast<LocalDecl>(expr);

            /// If the variable hasn’t already been allocated, do so now.
            if (not e->mlir) e->mlir = AllocateLocalVar(e);

            /// Handle construction.
            Construct(Loc(e->location), e->mlir, e->type.align(ctx), e->ctor);
        } break;

        /// If expressions.
        case Expr::Kind::IfExpr: {
            /// Emit the condition.
            auto e = cast<IfExpr>(expr);
            Generate(e->cond);

            /// Create the blocks that we need.
            bool has_yield = e->type.yields_value;
            auto cond_block = builder.getBlock();
            auto region = cond_block->getParent();
            auto then = new mlir::Block;
            auto join = e->type.is_noreturn ? nullptr : new mlir::Block;
            auto else_ = e->else_ ? new mlir::Block : join;
            auto if_loc = Loc(e->location);

            /// Add an argument to the join block if the expression
            /// yields a value.
            if (has_yield) {
                Assert(join);
                auto ty = Ty(e->type);
                if (e->is_lvalue) ty = hlir::ReferenceType::get(ty);
                join->addArgument(ty, if_loc);
            }

            /// Emit the conditional branch.
            Create<mlir::cf::CondBranchOp>(if_loc, e->cond->mlir, then, else_);

            /// Helper to emit a branch.
            auto EmitBranch = [&](Expr* expr, mlir::Block* block) {
                Attach(region, block);
                builder.setInsertionPointToEnd(block);
                Generate(expr);
                if (join) Create<mlir::cf::BranchOp>(
                    if_loc,
                    join,
                    has_yield ? expr->mlir : mlir::ValueRange{}
                );
            };

            /// Emit the then and else branches.
            EmitBranch(e->then, then);
            if (e->else_) EmitBranch(e->else_, else_);

            /// Finally, resume inserting in the join block.
            if (join) {
                Attach(region, join);
                builder.setInsertionPointToEnd(join);
                if (has_yield) e->mlir = join->getArgument(0);
            }
        } break;

        case Expr::Kind::WhileExpr: {
            auto w = cast<WhileExpr>(expr);

            /// Create a new block for the condition so we can branch
            /// to it and emit the condition there.
            auto region = builder.getBlock()->getParent();
            w->continue_block = Attach(region, new mlir::Block);
            Create<mlir::cf::BranchOp>(Loc(w->location), w->continue_block);
            builder.setInsertionPointToEnd(w->continue_block);
            Generate(w->cond);

            /// Emit the branch to the body.
            auto body = Attach(region, new mlir::Block);
            w->break_block = new mlir::Block;
            Create<mlir::cf::CondBranchOp>(Loc(w->location), w->cond->mlir, body, w->break_block);

            /// Emit the body.
            builder.setInsertionPointToEnd(body);
            Generate(w->body);
            Create<mlir::cf::BranchOp>(Loc(w->location), w->continue_block);

            /// Insert the join block and continue inserting there.
            Attach(region, w->break_block);
            builder.setInsertionPointToEnd(w->break_block);
        } break;

        /// Emit a for-in loop.
        ///
        /// If we are not iterating in reverse, this will emit the
        /// logical equivalent of:
        ///
        /// \code
        /// for (int __i = 0, __size = range.size; __i < __size; __i++) {
        ///     var iter = lvalue to range.data + __i;
        ///     <body>
        /// }
        /// \endcode
        ///
        /// If we are iterating in reverse, this will emit the logical
        /// equivalent of:
        ///
        /// \code
        /// for (int __i = size; __i > 0; __i--) {
        ///     var iter = lvalue to range.data + __i - 1;
        ///     <body>
        /// }
        /// \endcode
        case Expr::Kind::ForInExpr: {
            auto f = cast<ForInExpr>(expr);
            if (not isa<SliceType>(f->range->type)) Diag::ICE(
                ctx,
                f->range->location,
                "Sorry, we only support iterating over slices for now."
            );

            /// Emit the range, but not the iteration variable, since that
            /// one requires special handling as it’s not actually a variable.
            Generate(f->range);

            /// Get the size of the range.
            auto size = Create<hlir::SliceSizeOp>(
                builder.getUnknownLoc(),
                mlir::IndexType::get(mctx),
                f->range->mlir
            );

            /// Create the index used for the iteration. We just store the index
            /// in a block argument since it’s not exposed anyway.
            auto zero = Create<mlir::index::ConstantOp>(Loc(f->location), 0);
            auto region = builder.getBlock()->getParent();

            /// This needs to be a new block so we can branch to it.
            auto cond_block = Attach(region, new mlir::Block);
            cond_block->addArgument(mlir::IndexType::get(mctx), builder.getUnknownLoc());
            Create<mlir::cf::BranchOp>(
                Loc(f->location),
                cond_block,
                mlir::ValueRange{f->reverse ? size.getRes() : zero}
            );

            /// Test the condition.
            using Pred = mlir::index::IndexCmpPredicate;
            builder.setInsertionPointToEnd(cond_block);
            auto should_continue = Create<mlir::index::CmpOp>(
                builder.getUnknownLoc(),
                f->reverse ? Pred::UGT : Pred::ULT,
                cond_block->getArgument(0),
                f->reverse ? zero : size.getRes()
            );

            /// Branch depending on the condition. Also creat, but do not insert,
            /// the continue and break blocks here since any continue/break in
            /// the loop body will have to branch to one of them.
            auto body = Attach(region, new mlir::Block);
            f->continue_block = new mlir::Block;
            f->break_block = new mlir::Block;
            Create<mlir::cf::CondBranchOp>(
                builder.getUnknownLoc(),
                should_continue,
                body,
                f->break_block
            );

            /// Before emitting the body, get the slice data pointer and create
            /// a gep to the current index for the loop variable.
            builder.setInsertionPointToEnd(body);
            auto data = Create<hlir::SliceDataOp>(
                builder.getUnknownLoc(),
                f->range->mlir
            );

            /// Offset is `i` if we’re iterating forward and `i - 1` otherwise.
            mlir::Value offset = cond_block->getArgument(0);
            if (f->reverse) {
                offset = Create<mlir::index::SubOp>(
                    builder.getUnknownLoc(),
                    offset,
                    Create<mlir::index::ConstantOp>(Loc(f->location), 1)
                );
            }

            f->iter->emitted = true;
            f->iter->mlir = Create<hlir::OffsetOp>(
                builder.getUnknownLoc(),
                data,
                offset
            );

            /// Dew it.
            Generate(f->body);

            /// Increment/decrement the index and go back to the condition. This is also
            /// where we branch to in case of a continue.
            Attach(region, f->continue_block);
            if (not Closed(builder.getBlock())) Create<mlir::cf::BranchOp>(
                builder.getUnknownLoc(),
                f->continue_block
            );

            mlir::Value inc;
            builder.setInsertionPointToEnd(f->continue_block);
            if (f->reverse) {
                inc = Create<mlir::index::SubOp>(
                    builder.getUnknownLoc(),
                    cond_block->getArgument(0),
                    Create<mlir::index::ConstantOp>(Loc(f->location), 1)
                );
            } else {
                inc = Create<mlir::index::AddOp>(
                    builder.getUnknownLoc(),
                    cond_block->getArgument(0),
                    Create<mlir::index::ConstantOp>(Loc(f->location), 1)
                );
            }

            Create<mlir::cf::BranchOp>(
                builder.getUnknownLoc(),
                cond_block,
                mlir::ValueRange{inc}
            );

            /// Insert the break block and continue inserting there.
            Attach(region, f->break_block);
            builder.setInsertionPointToEnd(f->break_block);
        } break;

        case Expr::Kind::UnaryPrefixExpr: {
            auto u = cast<UnaryPrefixExpr>(expr);
            Generate(u->operand);
            switch (u->op) {
                default: Unreachable("Invalid unary operator: {}", Spelling(u->op));

                /// Negation.
                case Tk::Not: {
                    u->mlir = Create<hlir::NotOp>(
                        Loc(u->location),
                        u->operand->mlir
                    );
                } break;

                /// Dereference.
                case Tk::Star: {
                    u->mlir = Create<hlir::LoadOp>(
                        Loc(u->location),
                        u->operand->mlir
                    );
                } break;
            }
        } break;

        case Expr::Kind::SubscriptExpr: {
            auto f = cast<SubscriptExpr>(expr);
            if (not isa<SliceType>(f->object->type)) Diag::ICE(
                ctx,
                f->object->location,
                "Sorry, we only support subscripting slices for now."
            );

            Generate(f->index);
            Generate(f->object);

            auto ptr = Create<hlir::SliceDataOp>(
                Loc(f->location),
                f->object->mlir
            );

            f->mlir = Create<hlir::OffsetOp>(
                Loc(f->location),
                ptr,
                f->index->mlir
            );
        } break;

        case Expr::Kind::BinaryExpr: {
            auto b = cast<BinaryExpr>(expr);
            if (b->op == Tk::And or b->op == Tk::Or) {
                Generate(b->lhs);
                auto loc = Loc(b->location);
                auto rhs = new mlir::Block;
                auto res = new mlir::Block;
                res->addArgument(Ty(Type::Bool), loc);

                /// Then-block is rhs, else-block is res w/ false.
                if (b->op == Tk::And) {
                    Create<mlir::cf::CondBranchOp>(
                        loc,
                        b->lhs->mlir,
                        rhs,
                        mlir::ValueRange{},
                        res,
                        mlir::ValueRange{b->lhs->mlir}
                    );
                }

                /// Then-block is res w/ true, else-block is rhs.
                else {
                    Create<mlir::cf::CondBranchOp>(
                        loc,
                        b->lhs->mlir,
                        res,
                        mlir::ValueRange{b->lhs->mlir},
                        rhs,
                        mlir::ValueRange{}
                    );
                }

                /// Emit RHS.
                auto& r = builder.getBlock()->getParent()->getBlocks();
                r.insertAfter(builder.getBlock()->getIterator(), rhs);
                builder.setInsertionPointToEnd(rhs);
                Generate(b->rhs);
                Create<mlir::cf::BranchOp>(
                    loc,
                    res,
                    b->rhs->mlir
                );

                /// Join block.
                r.insertAfter(builder.getBlock()->getIterator(), res);
                builder.setInsertionPointToEnd(res);
                b->mlir = res->getArgument(0);
                break;
            }

            Generate(b->lhs);
            Generate(b->rhs);
            switch (b->op) {
                using namespace mlir::arith;
                using namespace hlir;
                default: Unreachable("Invalid binary operator: {}", Spelling(b->op));
                case Tk::Plus: GenerateBinOp<AddIOp>(b); break;
                case Tk::Minus: GenerateBinOp<SubIOp>(b); break;
                case Tk::Star: GenerateBinOp<MulIOp>(b); break;
                case Tk::StarStar: GenerateBinOp<mlir::math::IPowIOp>(b); break;
                case Tk::Slash: GenerateBinOp<DivSIOp>(b); break;
                case Tk::Percent: GenerateBinOp<RemSIOp>(b); break;
                case Tk::Xor: GenerateBinOp<XOrIOp>(b); break;
                case Tk::ShiftLeft: GenerateBinOp<ShLIOp>(b); break;
                case Tk::ShiftRight: GenerateBinOp<ShRSIOp>(b); break;
                case Tk::ShiftRightLogical: GenerateBinOp<ShRUIOp>(b); break;
                case Tk::EqEq: GenerateCmpOp<CmpIOp>(b, CmpIPredicate::eq); break;
                case Tk::Neq: GenerateCmpOp<CmpIOp>(b, CmpIPredicate::ne); break;
                case Tk::Lt: GenerateCmpOp<CmpIOp>(b, CmpIPredicate::slt); break;
                case Tk::Gt: GenerateCmpOp<CmpIOp>(b, CmpIPredicate::sgt); break;
                case Tk::Le: GenerateCmpOp<CmpIOp>(b, CmpIPredicate::sle); break;
                case Tk::Ge: GenerateCmpOp<CmpIOp>(b, CmpIPredicate::sge); break;
                case Tk::Land: GenerateBinOp<AndIOp>(b); break;
                case Tk::Lor:
                    GenerateBinOp<OrIOp>(b);
                    break;

                /// Compound assignment.
                case Tk::PlusEq: GenerateAssignBinOp<AddIOp>(b); break;
                case Tk::MinusEq: GenerateAssignBinOp<SubIOp>(b); break;
                case Tk::StarEq: GenerateAssignBinOp<MulIOp>(b); break;
                case Tk::StarStarEq: GenerateAssignBinOp<mlir::math::IPowIOp>(b); break;
                case Tk::SlashEq: GenerateAssignBinOp<DivSIOp>(b); break;
                case Tk::PercentEq: GenerateAssignBinOp<RemSIOp>(b); break;
                case Tk::ShiftLeftEq: GenerateAssignBinOp<ShLIOp>(b); break;
                case Tk::ShiftRightEq: GenerateAssignBinOp<ShRSIOp>(b); break;
                case Tk::ShiftRightLogicalEq: GenerateAssignBinOp<ShRUIOp>(b); break;

                /// Assignment and reference binding.
                case Tk::Assign:
                case Tk::RDblArrow: {
                    Create<hlir::StoreOp>(
                        Loc(b->location),
                        b->lhs->mlir,
                        b->rhs->mlir,
                        b->type.align(ctx).value()
                    );

                    /// Yields lhs as lvalue.
                    b->mlir = b->lhs->mlir;
                } break;
            }
        } break;

        /// This is the first parameter of the current function.
        case Expr::Kind::ImplicitThisExpr:
            expr->mlir = cast<hlir::FuncOp>(curr_proc->mlir_func).getImplicitThis();
            break;

        /// It is an error to have a ProcDecl directly referenced by anything that
        /// is not a DeclRefExpr or ScopeAccess. The reason for this is that we need
        /// to emit a ConstantOp for each use of the procedure, but we can’t do that
        /// every time it’s used if it’s the same procedure node.
        case Expr::Kind::ProcDecl: Diag::ICE(
            ctx,
            expr->location,
            "ProcDecl may only be ‘Generate()’d by a call to EmitReference()."
        );
    }
}

template <typename Op>
void src::CodeGen::GenerateAssignBinOp(src::BinaryExpr* b) {
    /// LHS is an lvalue, so load it first. Perform the binary
    /// operation and store the result back into the lvalue; the
    /// yield of the entire expression is the lvalue.
    auto align = b->type.align(ctx).value();
    auto lhs = Create<hlir::LoadOp>(Loc(b->lhs->location), b->lhs->mlir);
    auto res = Create<Op>(Loc(b->location), lhs, b->rhs->mlir);
    Create<hlir::StoreOp>(Loc(b->location), b->lhs->mlir, res, align);
    b->mlir = b->lhs->mlir;
}

template <typename Op>
void src::CodeGen::GenerateBinOp(src::BinaryExpr* b) {
    b->mlir = Create<Op>(
        Loc(b->location),
        b->lhs->mlir,
        b->rhs->mlir
    );
}

template <typename Op>
void src::CodeGen::GenerateCmpOp(BinaryExpr* b, mlir::arith::CmpIPredicate pred) {
    b->mlir = Create<Op>(
        Loc(b->location),
        pred,
        b->lhs->mlir,
        b->rhs->mlir
    );
}

void src::CodeGen::GenerateModule() {
    mctx->loadDialect<hlir::HLIRDialect>();

    /// Initialise MLIR module.
    mod->mlir_module_op = mlir::ModuleOp::create(
        Loc(mod->module_decl_location),
        mod->name.empty() ? "__exe__" : mod->name
    );

    /*    /// Set size of pointer.
        auto ptr_size = mlir::DataLayoutEntryAttr::get(
            hlir::ReferenceType::get(mlir::IntegerType::get(mctx, 1)),   /// Elem is irrelevant.
            mlir::IntegerAttr::get(mlir::IntegerType::get(mctx, 64), 64) /// FIXME: use context.
        );

        /// Crate data layout.
        mod->mlir->setAttr(
            mlir::DLTIDialect::kDataLayoutAttrName,
            mlir::DataLayoutSpecAttr::get(mctx, {ptr_size})
        );*/

    /// Codegen string literals.
    builder.setInsertionPointToEnd(mod->mlir.getBody());
    for (auto [i, s] : llvm::enumerate(mod->strtab)) {
        Create<hlir::StringOp>(
            builder.getUnknownLoc(),
            StringRef(s.data(), s.size()),
            APInt(64, u64(i))
        );
    }

    /// Codegen imports.
    builder.setInsertionPointToEnd(mod->mlir.getBody());
    for (auto& m : mod->imports) {
        for (auto& exp : m.mod->exports) {
            for (auto e : exp.second) {
                if (auto p = dyn_cast<ProcDecl>(e)) {
                    GenerateProcedure(p);
                } else if (isa<StructType>(e)) {
                    Generate(e);
                } else {
                    e->print(false);
                    Unreachable("Invalid import");
                }
            }
        }
    }

    /// Codegen functions.
    for (auto f : mod->functions) {
        builder.setInsertionPointToEnd(mod->mlir.getBody());
        GenerateProcedure(f);
    }

    /// Delete all function constants.
    mod->mlir.getBodyRegion().walk([](mlir::Operation* op) {
        if (isa<mlir::func::ConstantOp>(op)) op->erase();
    });

    /// Verify the IR.
    if (not no_verify and not mlir::succeeded(mod->mlir.verify()))
        Diag::ICE(ctx, mod->module_decl_location, "Module verification failed");
}

void src::CodeGen::GenerateProcedure(ProcDecl* proc) {
    tempset curr_proc = proc;

    /// Note that different modules, particularly C++ headers, may
    /// export the same procedures, so take care to only define them
    /// at most once.
    if (declared_procedures.contains(proc->mangled_name)) {
        auto func_op = declared_procedures[proc->mangled_name];

        /// If this is a declaration, just set the func op.
        if (not proc->body) {
            proc->mlir_func = func_op;
            return;
        }

        /// We can’t convert a declaration to a definition.
        Unreachable(
            "Procedure '{}' cannot be defined after it has been declared",
            proc->mangled_name
        );
    }

    /// Create the function.
    auto ptype = cast<ProcType>(proc->type);
    auto ty = Ty(ptype);
    auto func = Create<hlir::FuncOp>(
        Loc(proc->location),
        proc->mangled_name,
        ConvertLinkage(proc->linkage),
        mlir::LLVM::CConv::C,
        ty.cast<mlir::FunctionType>(),
        ptype->is_init,
        ptype->variadic
    );

    /// Associate the function with the procedure.
    proc->mlir_func = func;
    declared_procedures[proc->mangled_name] = func;

    /// If there is no body, drop the entry block.
    if (not proc->body) {
        func.eraseBody();
        func.setPrivate();
        return;
    }

    /// Entry block must be created first so we can access parameter values.
    builder.setInsertionPointToEnd(&func.front());

    /// Perform static construction.
    if (proc == mod->top_level_func) {
        if (mod->is_logical_module) {
            /// Create init guard variable.
            auto name = mod->init_guard_name();
            auto uloc = builder.getUnknownLoc();
            auto int32 = Ty(Type::I32);
            mlir::LLVM::GlobalOp init_guard;
            {
                mlir::OpBuilder::InsertionGuard guard{builder};
                builder.setInsertionPointToEnd(&cast<mlir::ModuleOp>(mod->mlir_module_op).getBodyRegion().back());
                init_guard = Create<mlir::LLVM::GlobalOp>(
                    uloc,
                    int32,
                    false,
                    mlir::LLVM::Linkage::Private,
                    name,
                    mlir::IntegerAttr::get(int32, 0),
                    Type::I32.align(ctx).value()
                );
            }

            /// Create init guard check.
            auto ref = Create<mlir::LLVM::AddressOfOp>(uloc, init_guard);
            auto one = Create<mlir::LLVM::ConstantOp>(uloc, int32, mlir::IntegerAttr::get(int32, 1));
            auto inc = Create<mlir::LLVM::AtomicRMWOp>(
                uloc,
                mlir::LLVM::AtomicBinOp::add,
                ref,
                one,
                mlir::LLVM::AtomicOrdering::acq_rel
            );

            /// Init if the old value was zero.
            auto zero = Create<mlir::LLVM::ConstantOp>(uloc, int32, mlir::IntegerAttr::get(int32, 0));
            auto cond = Create<mlir::arith::CmpIOp>(
                uloc,
                mlir::arith::CmpIPredicate::eq,
                inc.getResult(),
                zero
            );

            auto ret = new mlir::Block;
            auto init = new mlir::Block;
            Create<mlir::cf::CondBranchOp>(
                uloc,
                cond.getResult(),
                init,
                ret
            );

            builder.getBlock()->getParent()->push_back(ret);
            builder.setInsertionPointToEnd(ret);
            Create<hlir::ReturnOp>(uloc);

            builder.getBlock()->getParent()->push_back(init);
            builder.setInsertionPointToEnd(init);
        }

        /// Initialise imported modules.
        for (auto& i : mod->imports) {
            if (i.is_cxx_header) continue;
            Create<hlir::CallOp>(
                builder.getUnknownLoc(),
                mlir::TypeRange{},
                i.mod->module_initialiser_name(),
                false,
                mlir::LLVM::CConv::C
            );
        }
    }

    /// Create, but do not insert, blocks for all labels that are actually branched to.
    for (auto& [_, l] : proc->labels)
        if (l->used)
            l->block = new mlir::Block;

    /// Perform the transformations required to make local variables
    /// declared in this procedure accessible to its nested procedures.
    InitStaticChain(proc, func);

    /// Create local variables for parameters.
    for (auto [i, p] : llvm::enumerate(proc->params)) {
        p->emitted = true;
        p->mlir = AllocateLocalVar(p);

        /// TODO: Handle self-referential types.

        /// Store the initial parameter value in the variable.
        Create<hlir::StoreOp>(
            Loc(p->location),
            p->mlir,
            func.getExplicitArgument(u32(i)),
            p->type.align(ctx).value()
        );
    }

    /// Emit the body.
    Generate(proc->body);

    /// Insert a return expression at the end if there isn’t already one.
    ///
    /// Note: No need to worry about deferred expressions here or anything since
    /// that has already been taken care of by the code that emits the body.
    if (func.back().empty() or not func.back().back().hasTrait<mlir::OpTrait::IsTerminator>()) {
        /// Function returns void.
        if (proc->ret_type == Type::Void) {
            Create<hlir::ReturnOp>(Loc(proc->location));
        }

        /// Function does not return, or all paths return a value, but there
        /// is no return expression at the very end.
        else if (proc->ret_type == Type::NoReturn or not proc->body->implicit) {
            Create<hlir::UnreachableOp>(Loc(proc->location));
        }

        /// Function is a `= <expr>` function that returns its body.
        else {
            Assert(proc->body->mlir, "Inferred procedure body must yield a value");
            Create<hlir::ReturnOp>(
                Loc(proc->location),
                proc->body->mlir
            );
        }
    }
}
